---
image: bradrydzewski/ruby:2.0.0
env:
  - RAILS_ENV=test
  - SECRET_TOKEN=9747d0a1606e529a6bc18dbe3ebddbd9a748ae91201e157623f8aa43834e0a898bbf9342a91420580675a1050165f052fa8d58d1264f91b8bc152f3847aaebe8
script:
  - gem install bundler
  - bundle install
  - psql -c "create user shareup with createdb password 'shareup'" -U postgres -h 127.0.0.1
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
  - bundle exec rake rspec
services:
  - postgres
notify:
  email:
    recipients:
      - erwin@datarift.nl
  hipchat:
    room: {{hipchat_room}}
    token: {{hipchat_token}}
    on_started: true
    on_success: true
    on_failure: true