---
image: bradrydzewski/ruby:2.1.1
env:
  - RAILS_ENV=test
  - SECRET_TOKEN=9747d0a1606e529a6bc18dbe3ebddbd9a748ae91201e157623f8aa43834e0a898bbf9342a91420580675a1050165f052fa8d58d1264f91b8bc152f3847aaebe8
script:
  - echo "====== Setting up environment ======"
  - gem install bundler
  - bundle install
  - echo "====== Setting up database ======"
  - psql -c "update pg_database set datistemplate=false where datname='template1'" -U postgres -h 127.0.0.1
  - psql -c "drop database template1" -U postgres -h 127.0.0.1
  - psql -c "create database template1 with owner=postgres template=template0 encoding='UTF8'" -U postgres -h 127.0.0.1
  - psql -c "update pg_database set datistemplate=true where datname='template1'" -U postgres -h 127.0.0.1
  - psql -c "create user shareup with createdb password 'shareup'" -U postgres -h 127.0.0.1
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
  - echo "====== Running specs ======"
  - bundle exec rspec spec
services:
  - postgres
notify:
  email:
    recipients:
      - erwin@datarift.nl
  hipchat:
    room: {{hipchat_room}}
    token: {{hipchat_token}}
    on_started: true
    on_success: true
    on_failure: true