defaults: &defaults
  twitter:
    client_id: FPdy2R8J6JAyNr5W6g9wg
    client_secret: OZEQSHSuqg4sd5UbN2Vjq7P4hDOKC7Gf5Uxx6Mvb69s

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults